version: '3'
services:
  nocodb:
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    environment:
      NC_DB: "pg://user:password@host.docker.internal:5432/reboul_db"
    volumes:
      - ./nocodb_data:/usr/app/data
    restart: unless-stopped 