INSERT INTO products (
    name, brand, price, image_url, images, variants,
    category_id, description, tags, details, store_type,
    featured, created_at, brand_id, sku, active, new,
    _actiontype, store_reference, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ GEL1130 BLUE $$,
    $$ asics $$,
    0.0,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "43.5", "couleur": "BLUE", "stock": 1}]'::jsonb,
    NULL,
    $$  $$,
    ARRAY[]::text[],
    ARRAY[]::text[],
    $$  $$,
    FALSE,
    NULL,
    NULL,
    $$  $$,
    TRUE,
    FALSE,
    $$  $$,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, brand, price, image_url, images, variants,
    category_id, description, tags, details, store_type,
    featured, created_at, brand_id, sku, active, new,
    _actiontype, store_reference, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ GEL1130 BROWN $$,
    $$ asics $$,
    0.0,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "42.5", "couleur": "BROWN", "stock": 1}, {"taille": "43.5", "couleur": "BROWN", "stock": 1}]'::jsonb,
    NULL,
    $$  $$,
    ARRAY[]::text[],
    ARRAY[]::text[],
    $$  $$,
    FALSE,
    NULL,
    NULL,
    $$  $$,
    TRUE,
    FALSE,
    $$  $$,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, brand, price, image_url, images, variants,
    category_id, description, tags, details, store_type,
    featured, created_at, brand_id, sku, active, new,
    _actiontype, store_reference, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ GEL1130 WHBLK $$,
    $$ asics $$,
    0.0,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "41.5", "couleur": "WHBLK", "stock": 2}, {"taille": "42", "couleur": "WHBLK", "stock": 2}, {"taille": "42.5", "couleur": "WHBLK", "stock": 2}, {"taille": "43", "couleur": "WHBLK", "stock": 2}, {"taille": "44", "couleur": "WHBLK", "stock": 2}, {"taille": "44.5", "couleur": "WHBLK", "stock": 2}]'::jsonb,
    NULL,
    $$  $$,
    ARRAY[]::text[],
    ARRAY[]::text[],
    $$  $$,
    FALSE,
    NULL,
    NULL,
    $$  $$,
    TRUE,
    FALSE,
    $$  $$,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, brand, price, image_url, images, variants,
    category_id, description, tags, details, store_type,
    featured, created_at, brand_id, sku, active, new,
    _actiontype, store_reference, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ KAY14 BIRCH $$,
    $$ asics $$,
    0.0,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "40.5", "couleur": "BIRCH", "stock": 1}, {"taille": "41.5", "couleur": "BIRCH", "stock": 1}, {"taille": "42", "couleur": "BIRCH", "stock": 1}, {"taille": "42.5", "couleur": "BIRCH", "stock": 1}, {"taille": "43", "couleur": "BIRCH", "stock": 1}]'::jsonb,
    NULL,
    $$  $$,
    ARRAY[]::text[],
    ARRAY[]::text[],
    $$  $$,
    FALSE,
    NULL,
    NULL,
    $$  $$,
    TRUE,
    FALSE,
    $$  $$,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, brand, price, image_url, images, variants,
    category_id, description, tags, details, store_type,
    featured, created_at, brand_id, sku, active, new,
    _actiontype, store_reference, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ KAY14 BLACK $$,
    $$ asics $$,
    0.0,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "41", "couleur": "BLACK", "stock": 1}, {"taille": "42", "couleur": "BLACK", "stock": 1}, {"taille": "43", "couleur": "BLACK", "stock": 1}]'::jsonb,
    NULL,
    $$  $$,
    ARRAY[]::text[],
    ARRAY[]::text[],
    $$  $$,
    FALSE,
    NULL,
    NULL,
    $$  $$,
    TRUE,
    FALSE,
    $$  $$,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, brand, price, image_url, images, variants,
    category_id, description, tags, details, store_type,
    featured, created_at, brand_id, sku, active, new,
    _actiontype, store_reference, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ KINETIC GREY $$,
    $$ asics $$,
    0.0,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "42", "couleur": "GREY", "stock": 2}, {"taille": "42.5", "couleur": "GREY", "stock": 2}, {"taille": "43", "couleur": "GREY", "stock": 2}, {"taille": "44", "couleur": "GREY", "stock": 2}]'::jsonb,
    NULL,
    $$  $$,
    ARRAY[]::text[],
    ARRAY[]::text[],
    $$  $$,
    FALSE,
    NULL,
    NULL,
    $$  $$,
    TRUE,
    FALSE,
    $$  $$,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, brand, price, image_url, images, variants,
    category_id, description, tags, details, store_type,
    featured, created_at, brand_id, sku, active, new,
    _actiontype, store_reference, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ KINETIC PIEDM $$,
    $$ asics $$,
    0.0,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "42", "couleur": "PIEDM", "stock": 1}, {"taille": "42.5", "couleur": "PIEDM", "stock": 1}, {"taille": "43", "couleur": "PIEDM", "stock": 1}, {"taille": "44", "couleur": "PIEDM", "stock": 1}]'::jsonb,
    NULL,
    $$  $$,
    ARRAY[]::text[],
    ARRAY[]::text[],
    $$  $$,
    FALSE,
    NULL,
    NULL,
    $$  $$,
    TRUE,
    FALSE,
    $$  $$,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, brand, price, image_url, images, variants,
    category_id, description, tags, details, store_type,
    featured, created_at, brand_id, sku, active, new,
    _actiontype, store_reference, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ NIMBUS INDIGO $$,
    $$ asics $$,
    0.0,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "40.5", "couleur": "INDIGO", "stock": 2}, {"taille": "41.5", "couleur": "INDIGO", "stock": 2}, {"taille": "42", "couleur": "INDIGO", "stock": 2}, {"taille": "42.5", "couleur": "INDIGO", "stock": 2}, {"taille": "43", "couleur": "INDIGO", "stock": 2}]'::jsonb,
    NULL,
    $$  $$,
    ARRAY[]::text[],
    ARRAY[]::text[],
    $$  $$,
    FALSE,
    NULL,
    NULL,
    $$  $$,
    TRUE,
    FALSE,
    $$  $$,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, brand, price, image_url, images, variants,
    category_id, description, tags, details, store_type,
    featured, created_at, brand_id, sku, active, new,
    _actiontype, store_reference, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ NYC BLACK $$,
    $$ asics $$,
    0.0,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "41", "couleur": "BLACK", "stock": 1}, {"taille": "42", "couleur": "BLACK", "stock": 1}, {"taille": "43", "couleur": "BLACK", "stock": 1}]'::jsonb,
    NULL,
    $$  $$,
    ARRAY[]::text[],
    ARRAY[]::text[],
    $$  $$,
    FALSE,
    NULL,
    NULL,
    $$  $$,
    TRUE,
    FALSE,
    $$  $$,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, brand, price, image_url, images, variants,
    category_id, description, tags, details, store_type,
    featured, created_at, brand_id, sku, active, new,
    _actiontype, store_reference, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ NYC CREAM $$,
    $$ asics $$,
    0.0,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "42", "couleur": "CREAM", "stock": 1}, {"taille": "42.5", "couleur": "CREAM", "stock": 1}]'::jsonb,
    NULL,
    $$  $$,
    ARRAY[]::text[],
    ARRAY[]::text[],
    $$  $$,
    FALSE,
    NULL,
    NULL,
    $$  $$,
    TRUE,
    FALSE,
    $$  $$,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, brand, price, image_url, images, variants,
    category_id, description, tags, details, store_type,
    featured, created_at, brand_id, sku, active, new,
    _actiontype, store_reference, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ NYC CREAMROSE $$,
    $$ asics $$,
    0.0,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "42", "couleur": "CREAMROSE", "stock": 1}, {"taille": "42.5", "couleur": "CREAMROSE", "stock": 2}, {"taille": "43", "couleur": "CREAMROSE", "stock": 2}, {"taille": "44.5", "couleur": "CREAMROSE", "stock": 2}]'::jsonb,
    NULL,
    $$  $$,
    ARRAY[]::text[],
    ARRAY[]::text[],
    $$  $$,
    FALSE,
    NULL,
    NULL,
    $$  $$,
    TRUE,
    FALSE,
    $$  $$,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);