INSERT INTO products (
    name, description, price, category_id, brand_id,
    store_type, store_reference, active,
    brand, image_url, images, variants,
    tags, details, featured, created_at, sku,
    new, _actiontype, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ GEL1130 BLUE $$,
    $$  $$,
    0.0,
    20,
    37,
    $$ adult $$,
    $$ gel1130_blue $$,
    TRUE,
    $$ asics $$,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "43.5", "couleur": "BLUE", "stock": 1}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    FALSE,
    NULL,
    $$  $$,
    FALSE,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, description, price, category_id, brand_id,
    store_type, store_reference, active,
    brand, image_url, images, variants,
    tags, details, featured, created_at, sku,
    new, _actiontype, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ GEL1130 BROWN $$,
    $$  $$,
    0.0,
    20,
    37,
    $$ adult $$,
    $$ gel1130_brown $$,
    TRUE,
    $$ asics $$,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "42.5", "couleur": "BROWN", "stock": 1}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    FALSE,
    NULL,
    $$  $$,
    FALSE,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, description, price, category_id, brand_id,
    store_type, store_reference, active,
    brand, image_url, images, variants,
    tags, details, featured, created_at, sku,
    new, _actiontype, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ GEL1130 WHBLK $$,
    $$  $$,
    0.0,
    20,
    37,
    $$ adult $$,
    $$ gel1130_whblk $$,
    TRUE,
    $$ asics $$,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "41.5", "couleur": "WHBLK", "stock": 2}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    FALSE,
    NULL,
    $$  $$,
    FALSE,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, description, price, category_id, brand_id,
    store_type, store_reference, active,
    brand, image_url, images, variants,
    tags, details, featured, created_at, sku,
    new, _actiontype, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ KAY14 BIRCH $$,
    $$  $$,
    0.0,
    20,
    37,
    $$ adult $$,
    $$ kay14_birch $$,
    TRUE,
    $$ asics $$,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "40.5", "couleur": "BIRCH", "stock": 1}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    FALSE,
    NULL,
    $$  $$,
    FALSE,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, description, price, category_id, brand_id,
    store_type, store_reference, active,
    brand, image_url, images, variants,
    tags, details, featured, created_at, sku,
    new, _actiontype, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ KAY14 BLACK $$,
    $$  $$,
    0.0,
    20,
    37,
    $$ adult $$,
    $$ kay14_black $$,
    TRUE,
    $$ asics $$,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "41", "couleur": "BLACK", "stock": 1}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    FALSE,
    NULL,
    $$  $$,
    FALSE,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, description, price, category_id, brand_id,
    store_type, store_reference, active,
    brand, image_url, images, variants,
    tags, details, featured, created_at, sku,
    new, _actiontype, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ KINETIC GREY $$,
    $$  $$,
    0.0,
    20,
    37,
    $$ adult $$,
    $$ kinetic_grey $$,
    TRUE,
    $$ asics $$,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "42", "couleur": "GREY", "stock": 2}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    FALSE,
    NULL,
    $$  $$,
    FALSE,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, description, price, category_id, brand_id,
    store_type, store_reference, active,
    brand, image_url, images, variants,
    tags, details, featured, created_at, sku,
    new, _actiontype, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ KINETIC PIEDM $$,
    $$  $$,
    0.0,
    20,
    37,
    $$ adult $$,
    $$ kinetic_piedm $$,
    TRUE,
    $$ asics $$,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "42", "couleur": "PIEDM", "stock": 1}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    FALSE,
    NULL,
    $$  $$,
    FALSE,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, description, price, category_id, brand_id,
    store_type, store_reference, active,
    brand, image_url, images, variants,
    tags, details, featured, created_at, sku,
    new, _actiontype, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ NIMBUS INDIGO $$,
    $$  $$,
    0.0,
    20,
    37,
    $$ adult $$,
    $$ nimbus_indigo $$,
    TRUE,
    $$ asics $$,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "40.5", "couleur": "INDIGO", "stock": 2}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    FALSE,
    NULL,
    $$  $$,
    FALSE,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, description, price, category_id, brand_id,
    store_type, store_reference, active,
    brand, image_url, images, variants,
    tags, details, featured, created_at, sku,
    new, _actiontype, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ NYC BLACK $$,
    $$  $$,
    0.0,
    20,
    37,
    $$ adult $$,
    $$ nyc_black $$,
    TRUE,
    $$ asics $$,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "41", "couleur": "BLACK", "stock": 1}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    FALSE,
    NULL,
    $$  $$,
    FALSE,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, description, price, category_id, brand_id,
    store_type, store_reference, active,
    brand, image_url, images, variants,
    tags, details, featured, created_at, sku,
    new, _actiontype, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ NYC CREAM $$,
    $$  $$,
    0.0,
    20,
    37,
    $$ adult $$,
    $$ nyc_cream $$,
    TRUE,
    $$ asics $$,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "42", "couleur": "CREAM", "stock": 1}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    FALSE,
    NULL,
    $$  $$,
    FALSE,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);

INSERT INTO products (
    name, description, price, category_id, brand_id,
    store_type, store_reference, active,
    brand, image_url, images, variants,
    tags, details, featured, created_at, sku,
    new, _actiontype, material, weight,
    dimensions, rating, reviews_count
) VALUES (
    $$ NYC CREAMROSE $$,
    $$  $$,
    0.0,
    20,
    37,
    $$ adult $$,
    $$ nyc_creamrose $$,
    TRUE,
    $$ asics $$,
    $$  $$,
    ARRAY[]::text[],
    '[{"taille": "42", "couleur": "CREAMROSE", "stock": 1}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    FALSE,
    NULL,
    $$  $$,
    FALSE,
    $$  $$,
    $$  $$,
    NULL,
    $$  $$,
    NULL,
    0
);